name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

env:
  GO_VERSION: '1.20'

jobs:
  test:
    name: test go files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests with code coverage report
        run: go test -v ./... -coverprofile="coverage.out"
